### ISSUE TITLE
UPower clients don't receive signals from the server

### ISSUE THREAD

**Issue by sergio-costas** [canonical/ubuntu-core-desktop#32]
UPower clients usually connects to the standard DBus signal _org.freedesktop.DBus.Properties.PropertiesChanged_ to detect changes in the properties of a device, like the battery percentage or the charging/on-battery flag. But, for some reason, in the current images of _ubuntu-core-desktop_, this signal isn't received by the clients if they are snapped. In a normal Ubuntu desktop, the same snap does receive the notifications. Also, running the binary outside the snap, as root, it does receive the signals.

The current SNAPD code has specific apparmor configuration to allow to pass the PropertiesChanged signals:

![imagen](https://user-images.githubusercontent.com/105285003/207280213-6f95f851-572a-44b1-b02d-2810b1d731b1.png)

To test this, you can download this snap: https://drive.google.com/file/d/1nsPB2amxZaqy5uy5bLAKg2mpvXqmq_L8/view?usp=share_link

Installing it in the system and running it with "snap run upower-test" will show all the properties for the path "/org/freedesktop/UPower/devices/battery_BAT0". Any change on their properties will also be notified (like when the power cord is connected/disconnected).

Running it in a classic Ubuntu desktop, it will work fine (as long as the "upower-observer" plug is connected, of course).

Running it in an ubuntu-core-desktop laptop will read all the properties, but won't detect the signals.

In the same ubuntu-core-desktop system, going to the root terminal and running it directly ("/snap/upower-test/current/usr/bin/upower") will work fine, showing all the properties and detecting the signals.

**Comment by sergio-costas** [comment]
Agh! I removed it yesterday, sorry. I'll upload it again.

**Comment by sergio-costas** [comment]
Ok, I updated the link in the previous comment: https://drive.google.com/file/d/1nsPB2amxZaqy5uy5bLAKg2mpvXqmq_L8/view?usp=share_link

**Comment by kenvandine** [comment]
I think this is now working as expected on the ubuntu-core-desktop device, can the issue be closed?

**Comment by sergio-costas** [comment]
Yes, it does work. I'll close this.
