### ISSUE TITLE
Hint and tips for budgie

### ISSUE THREAD

**Issue by fossfreedom** [canonical/ubuntu-core-desktop#48]
I have been looking at this project to examine whether an immutable version of the budgie desktop is possible.

I have been looking at adding and removing snaps, generating  images etc.

I can see that I will need a slight tweaks and a tuck with the ubuntu-session snap for us.

But I am missing the obvious ... what is the snap/snaps project(s) that is/are actually installing gnome-shell plus GDM?  Initially I would need to look at substituting gnome-shell with budgie. Eventually replacing GDM with lightdm or similar. 

TIA

**Comment by kenvandine** [comment]
@fossfreedom it's great to see interest in creating a budgie version based on core desktop.  It will be totally doable, and we'll provide documentation and happy to collaborate during that process, but we're not quite for that yet.  Let's chat about this a bit during one of the flavor syncs.
