### ISSUE TITLE
save file dialog defaults to wrong download location

### ISSUE THREAD

**Issue by hellsworth** [canonical/ubuntu-core-desktop#51]
I have the simple-scan snap in candidate (44.0, Rev 792) on a core desktop system. When I scan a document and click the download button, the default location it tries to open, as a suggested download location, gives a permissions error. This is because the default location opened is `/run/user/1001/doc`, which nobody will have access to. This happens on the firefox snap as well, so I suspect this is a shared issue.

![Screenshot from 2023-07-27 12-28-04](https://github.com/ubuntu/simple-scan/assets/12970280/ac73fc9f-eac9-4751-ae55-3abba8f52769)

![Screenshot from 2023-07-14 13-55-08](https://github.com/canonical/ubuntu-core-desktop/assets/12970280/ae825de7-2659-486a-9986-99ed9a5e4c38)

You can still click OK and then go select another location like ~/Downloads and download the document just fine though.

**Comment by kenvandine** [comment]
This has been fixed
