### ISSUE TITLE
Where’s the download link?

### ISSUE THREAD

**Issue by wjk** [canonical/ubuntu-core-desktop#61]
I can’t wait to try out Ubuntu Core Desktop. After reading about it on one of the computer news sites, I think it is an awesome idea. I even installed the openSUSE version of this and tried it out, using KDE and Flatpak instead of GNOME and Snap. I would love to try out your version.

I have found this repo, and its README gives me very helpful instructions on how to run it. However, the README references that there are two images to download. I cannot find a link to download these images anywhere! DuckDuckGo does not give me anything useful, and I understand the regular Core images do not come with a desktop.

Furthermore, are there any plans on building a general-use ARM64 build of this project? I run an M1 Mac, and therefore am unable run many Linux distributions (including regular Ubuntu) because they only provide binaries for Intel. (I understand that the Raspberry Pi images only include support for the Raspberri Pi’s specific bootloader, and will not work under standard UEFI. I am happy to be proved wrong, though.)

**Comment by sandmuel** [comment]
Go into the 'Actions' tab and select the latest one that doesn't have an `x`, the `x` means it failed to build. Note that it's not meant for daily driving *yet* and last I tried it didn't add the user to the wheel group, so they have to leave the root password empty and unlocked. Note that whatever the image is flashed to is what it will install to.

**Comment by wjk** [comment]
Unfortunately, the expanded file is too big for my filesystem to handle. (I believe the full uncompressed size is 20GB, but my entire system crashed after it extracted 2.1GB.) Thanks nevertheless!
