### ISSUE TITLE
Self-built snap image doesn’t use snap

### ISSUE THREAD

**Issue by wjk** [canonical/ubuntu-core-desktop#67]
I have set up a regular Ubuntu VM, and used it to build an image I can boot in my VM software. I built this image using `make pc.img` in the root directory of this repo, with no modifications. However, the output image is a regular (non-Core) live image, with only one snap installed, which is not what I want. This happens despite the build process spending a good chunk of time downloading and unpacking snaps. What’s going wrong?

**Comment by kenvandine** [comment]
Sorry, I can't reproduce this.  When I run that command I get the bootable core desktop disk image.  

What does the disk layout look like?  Run this command:

```
fdisk -l pc.img
```

**Comment by kenvandine** [comment]
That looks right, how are booting that image?

**Comment by wjk** [comment]
Via a VM program called [UTM](https://mac.getutm.app/), which is based on QEMU. The exact QEMU command line is as follows (line-wrapped for readability):

```
qemu-system-aarch64 -L /Applications/UTM.app/Contents/Resources/qemu -S 
-spice unix=on,addr=309DC44B-FDEE-4085-9696-2A1DB431BF57.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off
-chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0
-mon chardev=org.qemu.monitor.qmp,mode=control
-nodefaults
-vga none
-device virtio-net-pci,mac=D2:DA:B2:64:6C:3B,netdev=net0
-netdev vmnet-shared,id=net0 -device virtio-gpu-pci
-cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt
-accel hvf
-drive if=pflash,format=raw,unit=0,file.filename=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,file.locking=off,readonly=on
-drive "if=pflash,unit=1,file=/Users/williamkent/Library/Containers/com.utmapp.UTM/Data/Documents/Ubuntu Core Desktop.utm/Data/efi_vars.fd"
-m 4096
-audiodev spice,id=audio0
-device intel-hda -device hda-duplex,audiodev=audio0
-device nec-usb-xhci,id=usb-bus
-device usb-tablet,bus=usb-bus.0
-device usb-mouse,bus=usb-bus.0
-device usb-kbd,bus=usb-bus.0
-device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0
-device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0
-chardev spicevmc,name=usbredir,id=usbredirchardev1 
-device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0
-chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0
-device usb-storage,drive=driveF59907E3-C9AA-4785-9B82-CE94FEDCCAF3,removable=true,bootindex=0,bus=usb-bus.0
-drive "if=none,media=cdrom,id=driveF59907E3-C9AA-4785-9B82-CE94FEDCCAF3,file=/Users/williamkent/Documents/Virtual Machines/jammy-desktop-arm64.iso,readonly=on"
-device virtio-serial
-device virtserialport,chardev=org.qemu.guest_agent,name=org.qemu.guest_agent.0
-chardev spiceport,id=org.qemu.guest_agent,name=org.qemu.guest_agent.0
-device virtserialport,chardev=vdagent,name=com.redhat.spice.0
-chardev spicevmc,id=vdagent,debug=0,name=vdagent -fsdev "local,id=virtfs0,path=/Users/williamkent/Documents/Virtual Machines/Shared,security_model=mapped-xattr"
-device virtio-9p-pci,fsdev=virtfs0,mount_tag=share
-name "Ubuntu Core Desktop"
-uuid 309DC44B-FDEE-4085-9696-2A1DB431BF57
-device virtio-rng-pci
```

**Comment by wjk** [comment]
Please accept my apologies. The image built is very much a Core Desktop image, with all the expected snaps present. I was looking in the wrong folders when I first filed this issue. Sorry for the trouble!

**Comment by wjk** [comment]
And I spoke too soon. Here is a screenshot of my `/snap` folder:

<img width="893" alt="Screenshot 2023-12-12 at 11 59 56 AM" src="https://github.com/canonical/ubuntu-core-desktop/assets/1915951/dc3b65c6-5557-47bf-80e0-d584c11fafef">

I think there should be more snaps than these, and far fewer apt packages (of which there are a great many of, despite this being the Core Desktop image).

**Comment by wjk** [comment]
Important detail I left out: I am building the image for ARM64. My apologies for not mentioning this earlier.

**Comment by kenvandine** [comment]
How are you building it?  The only arm64 gadget we have is for the Pi4, which would build a pi.img disk image.  There isn't a way to build a generic arm64 image.

**Comment by wjk** [comment]
:sad pikachu:

I find it annoying how many people release only release Intel versions of their products. People running “generic arm64” are now a significant fraction of the population due to the processors used in modern Macs.

I would want to submit a PR to fix this, but the required integration with the Snap Store makes contributing difficult. I do not know how to write or debug a kernel or gadget snap locally on my computer, for example. I also don’t how how to determine the `id` codes used to identify snaps, and I don’t know how to turn a `.json` file into a `.model` file I can use with `ubuntu-image`. Some pointers would be helpful.

**Comment by kenvandine** [comment]
All of the snaps we include are built for arm64, but arm64 devices aren't like x86.  There isn't really such a thing as generic arm64.  We've done the enablement for the raspberry pi, and we should see more  arm64 devices over time.

**Comment by wjk** [comment]
Yep!
