### ISSUE TITLE
Ubuntu Core Desktop Size

### ISSUE THREAD

**Issue by jaredhagel** [canonical/ubuntu-core-desktop#69]
Our company is interested in evaluating the Ubuntu Core Desktop, but one major concern we have is image size. Devices we run are constrained to 16GB. Ubuntu Core was designed to have a small image size ("...image size of 260MB..." from https://www.zdnet.com/article/ubuntu-core-doubles-down-on-internet-of-things/). Is this the same case with Ubuntu Core Desktop? I wasn't sure if size was much of a consideration with Ubuntu Core Desktop since GNOME desktop is used. Or maybe this is configurable?

**Comment by robert-ancell** [comment]
The size is not configurable and is currently quite large. At this point we're just expanding the size as necessary to make things work. At some future time we'll look at minimizing the size to be as small as possible.

**Comment by kenvandine** [comment]
> Our company is interested in evaluating the Ubuntu Core Desktop, but one major concern we have is image size. Devices we run are constrained to 16GB. Ubuntu Core was designed to have a small image size ("...image size of 260MB..." from https://www.zdnet.com/article/ubuntu-core-doubles-down-on-internet-of-things/). Is this the same case with Ubuntu Core Desktop? I wasn't sure if size was much of a consideration with Ubuntu Core Desktop since GNOME desktop is used. Or maybe this is configurable?

The generic images aren't configurable, however you would ultimately want to create your own images.  Keeping it under 16G should be no problem, depending on what snaps you need to include.  Feel free to tag me directly if you have any questions about that.
